name: CI

on:
  pull_request:      

jobs:
 
  CI:
    name: "CI"
    runs-on: Windows
    timeout-minutes: 60
    steps:
      - name: Check out the GM-TestFramework repo
        uses: actions/checkout@v4
        with:
          path: GM-TF
      - name: Wait for 10 Minutes
        run: Start-Sleep -Seconds 300
        shell: pwsh
      - name: Testing on PR
        run: ./launcher igorRunTests --config-file "C:\GM-TestFramework\configs\${{ github.event.inputs.CONFIG_FILE }}" --feed 'https://gms.yoyogames.com/Zeus-Runtime-Nocturnus-I.rss' ${{ github.event.inputs.EXTRA_PARAMS }}
        working-directory: GM-TF
        shell: pwsh
      - name: Upload Results Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: summary_file
          path: ${{ github.workspace }}\GM-TF\results

        
      
