name: CI

on:
  pull_request:      

jobs:
 
  CI:
    name: "CI"
    runs-on: Windows
    timeout-minutes: 120
    steps:
      - name: Check out the GM-TestFramework repo
        uses: actions/checkout@v4
        with:
          path: GM-TF
      - name: Wait for 10 Minutes
        run: Start-Sleep -Seconds 300
        shell: pwsh        
      - run: .\setup.bat
        working-directory: GM-TF
        shell: cmd                  
      - name: Testing on PR    
        run: run_ci.bat C:\GM-TestFramework\configs\config_windows.json https://gms.yoyogames.com/Zeus-Runtime-Nocturnus-I.rss       
        working-directory: GM-TF   
        shell: cmd        
      - name: Upload Results Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: summary_file
          path: ${{ github.workspace }}\GM-TF\results

        
      
