name: Red

on:

  workflow_dispatch:
    inputs:
       CONFIG_FILE:
         description: "CONFIG_FILE"
         required: true
       RSS_Feed:
         description: "RSS_Feed"
         required: false
         type: string
       EXTRA_PARAMS:
          description: "EXTRA_PARAMS from config"
          required: false
          type: string         

jobs:
 
  CI:
    name: "CI"
    runs-on: Windows
    timeout-minutes: 60
    steps:
      - name: Check out the GM-TestFramework repo
        uses: actions/checkout@v4
        with:
          path: GM-TF
      - name: Wait for 10 Minutes
        run: Start-Sleep -Seconds 300
        shell: pwsh     
      - name: Testing Manually with passing RSS_Feed for Red builds
        run: ./launcher igorRunTests --config-file "C:\GM-TestFramework\configs\${{ github.event.inputs.CONFIG_FILE }}" ${{ github.event.inputs.EXTRA_PARAMS }}
        working-directory: GM-TF  
        shell: pwsh         
      - name: Upload Results Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: summary_file
          path: ${{ github.workspace }}\GM-TF\results
      - name: Running TF Compare Script
        run: python .\tf_compare.py --github-token ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} --workflow  ${{ github.workflow }}.yml
        working-directory: GM-TF          
      - name: Upload TF Compare Output
        if: always()
        uses: actions/upload-artifact@v4
        with:
           name: tf_compare_output_file
           path: ${{ github.workspace }}\GM-TF\TF_Output.txt
        
      
