name: Test

on:

  workflow_dispatch:
    inputs:
       CONFIG_FILE:
         description: "CONFIG_FILE"
         required: true
       RSS_Feed:
         description: "RSS_Feed"
         required: false
         type: string
       EXTRA_PARAMS:
          description: "EXTRA_PARAMS from config"
          required: false
          type: string  
       RUNTIME_VERSION:
          description: "Full Runtime Version"
          required: true
          type: string       

jobs:
 
  Red:
    name: "Red"
    runs-on: Windows
    timeout-minutes: 60
    steps:
      - name: Read test stats
        run: |
            # Read the contents of the slack_stats.json file
            $stats = Get-Content "C:\\GM-TestFramework\\slack_stats.json" -Raw
            # Convert the content to JSON format
            $statsJson = $stats | ConvertFrom-Json

            # Check that the content has been parsed correctly
            Write-Host "Parsed Stats: $($statsJson | ConvertTo-Json -Depth 3)" # Increased depth for better visibility

            # Ensure fields are populated correctly
            if ($statsJson.attachments[0].fields -eq $null -or $statsJson.attachments[0].fields.Count -eq 0) {
                Write-Host "No fields found in stats JSON."
            } else {
                # Format the fields into a human-readable string
                $formattedFields = $statsJson.attachments[0].fields | ForEach-Object {
                    "*$($_.title)*: $($_.value)"
                }
    
                # Join all formatted fields into a single string with new lines
                $statsFormatted = $formattedFields -join "`n"
                # Output to environment variable for use in Slack message
                echo "STATS=$statsFormatted" >> $GITHUB_ENV
                Write-Host "Formatted Stats: $statsFormatted"
              }
        shell: pwsh
      - name: Send Test Stats to Slack
        uses: slackapi/slack-github-action@v2.0.0
        with:
        #   payload: |
        #     {
        #       "channel": "C07AMRFCC0P",
        #       "username": "${{ github.actor }}",
        #       "icon_url": "https://github.com/black.png?size=48",
        #       "attachments": [
        #         {
        #           "color": "${{ job.status == 'success' && 'good' || 'danger' }}",
        #           "title": "GM-TestFramework Monthly Build ${{ github.run_number }} Testframework Build with Runtime version ${{ github.event.inputs.RUNTIME_VERSION }} is *${{ job.status }}*",
        #           "text": "${{ env.STATS }}"
        #         }
        #       ]
        #     }
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload-file-path: "C:\\GM-TestFramework\\slack_stats.json"
          payload-templated: true
        
      
